# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: thennarasu.com
# Description of the Site
description: personal portal
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/thennarasug/thennarasug.github.io/master/assets/images/sk_wallpaper.png
# Keywords of the Site
site-keywords: thennarasu, thennarasug, thennarasu gopalsamy, dino, sk, thennarasu.com
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/thennarasug/thennarasug.github.io/master/assets/images/pexels-luis-gomes-546819.jpg
#https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: contact@thennarasu.com
twitter_username: 5k6m
linkedin_username: thennarasug
github_username:  thennarasug
youtube_channel_id: UCk9u3MG5e4YqMyqXkzIZ_Jw
reddit_username: s0uthk1ng

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: testtesttestdisqus1234qwer

# Name of the Author
author-name: thennarasu
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/thennarasug/thennarasug.github.io/master/assets/images/sk.png
# 60 Words About the Author
author-about: 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://thennarasu.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
